name: six
on:
  push:
    branches: ['workflows6']
jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jmoyano/cautious-meme
          ref: main
      - run: gcc main.c -o main
      - uses: actions/upload-artifact@v3
        with:
          name: envoutput
          path: ./main
  test:
    name: 'test-download'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:    
          name: envoutput
      - run: ls
      - run: python verificacion.py  
